import os
import whisperx
from openai import OpenAI
import warnings
import time

warnings.filterwarnings("ignore")

# ✅ Step 1: Set up OpenAI client using environment variable
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    print("Error: OPENAI_API_KEY not set.")
    exit(1)

client = OpenAI(api_key=api_key)

# ✅ Step 2: Transcribe audio with WhisperX
def transcribe_audio(audio_file):
    device = "cpu"  # Change to "cuda" or "mps" if you have GPU support
    model = whisperx.load_model("large-v3", device=device, compute_type="float32")
    audio = whisperx.load_audio(audio_file)
    result = model.transcribe(audio)
    print("Transcription complete. Aligning words...")
    model_a, metadata = whisperx.load_align_model(language_code=result["language"], device=device)
    aligned_result = whisperx.align(result["segments"], model_a, metadata, audio, device=device)
    full_text = " ".join(segment["text"].strip() for segment in aligned_result["segments"])
    return full_text

# ✅ Step 3: Load appropriate judging prompt
def load_prompt(style, topic, first_team, transcript_text):
    style = style.strip().lower()
    if style == "tech":
        prompt_path = "tech_judge_prompt.txt"
    elif style in ["lay", "flay"]:
        prompt_path = "lay_judge_prompt.txt"
    else:
        print("❌ Invalid style. Please enter 'lay', 'flay', or 'tech'.")
        exit(1)

    try:
        with open(prompt_path, "r", encoding="utf-8") as f:
            prompt_template = f.read()
    except FileNotFoundError:
        print(f"Error: {prompt_path} not found.")
        exit(1)

    filled_prompt = (
        prompt_template
        .replace("[insert topic here]", topic)
        .replace("[insert team name here]", first_team)
        .replace("[insert transcript here]", transcript_text)
    )

    return filled_prompt

# ✅ Step 4: Analyze debate using GPT-4o
def analyze_debate(prompt):
    messages = [
        {"role": "system", "content": "You are an AI debate judge for Public Forum rounds."},
        {"role": "user", "content": prompt}
    ]
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=messages,
            temperature=0,
            max_tokens=3500
        )
        return response.choices[0].message.content
    except Exception as e:
        print("❌ OpenAI API Error:", e)
        return None

# ✅ Step 5: Main runner
if __name__ == "__main__":
    audio_file = input("🎙️ Enter the name of the debate audio file (e.g., round1.m4a): ")
    topic = input("🗣️ Enter the debate topic: ")
    first_team = input("🏁 Which side spoke first (Aff or Neg)? ")
    style = input("🎛️ Was this debate lay / flay / tech (200+ wpm)? ").strip().lower()

    if style not in ["lay", "flay", "tech"]:
        print("❌ Invalid input. Please type only 'lay', 'flay', or 'tech'.")
        exit(1)

    start_time = time.time()

    try:
        transcript_text = transcribe_audio(audio_file)
    except Exception as e:
        print("❌ WhisperX transcription failed:", e)
        exit(1)

    try:
        with open("transcript.txt", "w", encoding="utf-8") as f:
            f.write(transcript_text)
    except Exception as e:
        print("❌ Could not write transcript to file:", e)

    prompt = load_prompt(style, topic, first_team, transcript_text)
    feedback = analyze_debate(prompt)

    if feedback:
        print("\n=== 🧠 AI Judge Feedback ===\n")
        print(feedback)

        with open("judging_feedback.txt", "w", encoding="utf-8") as txt_file:
            txt_file.write(feedback)

        elapsed = time.time() - start_time
        print(f"\n✅ Feedback saved to judging_feedback.txt")
        print(f"⏱️ Total time: {round(elapsed, 2)} seconds")
    else:
        print("❌ No feedback generated by GPT.")
